version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      - NODE_ENV=docker
    ports:
      - '27017:27017'

  backend-api:
    build:
      context: ./backend-api
    ports:
      - '8088:8088'
    environment:
      - NODE_ENV=docker
    depends_on:
      - mongodb

  ml-model-service:
    build:
      context: ./ml-model-service
    ports:
      - '5001:5001'

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_BASE_URL_CLIENT=http://backend-api:8088
    depends_on:
      - backend-api
