version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - '27018:27017'
    networks:
      - dark_pattern_network
    volumes:
      - mongo-data:/data/db

  backend-api:
    build:
      context: ./backend-api
    ports:
      - '8088:8088'
    environment:
      - NODE_ENV=docker
    depends_on:
      - mongo
    networks:
      - dark_pattern_network

  ml-model-service:
    build:
      context: ./ml-model-service
    ports:
      - '5001:5001'
    networks:
      - dark_pattern_network

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend-api
    networks:
      - dark_pattern_network

networks:
  dark_pattern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local